version: '3'

services:

  cutiapp-service:
    image: ihsanyoandocker/cutiapp:v1.0.0
    container_name: cutiapp-service
    hostname: cutiapp-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 8080:8080
    volumes:
      - ./app-config/cutiapp.yml:/app/application-dev.yml
